name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs_validate:
    runs-on: "ubuntu-latest"
    name: "HACS validation"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        uses: "hacs/integration/action@main"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CATEGORY: "plugin"
  eslint_validate:
    runs-on: "ubuntu-latest"
    name: "ESLint validation"
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        npm install eslint --save-dev
        npx eslint --init
    - name: Run ESLint
      run: npx eslint . --ext .js,.ts
